services:
  db:
    image: mysql:8.0
    container_name: innoviahub-mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db/init:/docker-entrypoint-initdb.d
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  db_data:
